### ISSUE TITLE
ApplicationBuilder should initialize gtk as well

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#143] opened 2021-01-01 21:31 UTC
From IRC
> dcomp: Whats the difference between gtk4::Application::new and gtk4::ApplicationBuilder::new().build()? 
I would assume that the Builder just calls methods on a Application instance. But that doesn't seem to be the case
as I get a panic on the activate signal saying that gtk::init hasn't been called

-> bilelmoussaoui :  slomo: it needs it here as well https://github.com/gtk-rs/gtk4-rs/blob/master/gtk4/src/auto/application.rs#L65 i guess

**Comment by sdroege** [comment] 2021-01-01 22:11
Duplicate of https://github.com/gtk-rs/gtk4-rs/issues/118 or not?

**Comment by bilelmoussaoui** [comment] 2021-01-01 22:34
Not at all, we just need to manually add that builder and call `rt.init();` while the other issue is related to subclassing `gtk::Application`

**Closed** 2021-01-11 08:17 UTC
Labels: bug, good first issue, gtk
